"""
Project Euler Problem #2
=========================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""


def fib(start = 0):
    sum = 0
    a, b, erg = 0, 1, 0
    while erg < start:
        erg, a , b = a + b, b, a + b
        if erg % 2 == 0:
            sum = sum + erg
    return sum

print fib(4000000)
