"""
Project Euler Problem #12
==========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import math

def get_primfakt_old(n):
    l = []
    while n != 1:
        for x in range(2,n+1):
            if n % x == 0:
                l.append(x)
                n /= x
                break
    return l

def get_primfakt(n):
    l = []
    s = set()
    count = 1
    if n % 2 == 0:
        n /= 2
    while n != 1:
        for x in range(2,n+1):
            if n % x == 0:
                l.append(x)
                s.add(x)
                n /= x
                break
    for zahl in s:
        count *= (1 + l.count(zahl))
    return count

def return_result():
    counter = 1
    lnum, rnum = get_primfakt(counter), get_primfakt(counter + 1)
    while lnum * rnum < 500:
        counter+=1
        lnum, rnum = rnum, get_primfakt(counter + 1)
    return counter


index = return_result()
print (index * (index + 1 ))/2 
